# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages

on:
  push:
    paths:
      - index.html
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#permission
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload site
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2

